---
title: "Teaching"
---

# Teaching at IUB

### Grading and holding office hours
* S420/620 Introduction to Statistical Theory (Spring 2013, B. Luen)
* S432/632 Applied Linear Models II (Spring 2013, C. Huang)
* S431/631 Applied Linear Models I (Fall 2012, C. Huang)
* S426/626 Bayesian Theory and Data Analysis (Fall 2012, G. Huerta, now at Univeristy of New Mexico).
* K310 Statistical Techniques (Spring 2012, S. Sang, now at University of Mississippi)

### Lab sections
* S501 Statistical methods (Fall 2011, W. Wyatt)
* R workshop (Fall 2012, T. Jackson)




# Teaching at UCSC

### Grading and discussion sections
* AMS7 Statistical Methods for the Biological, Environmental, and Health Sciences (Spring 2016, T. Xifara; Summer 2015, B. Mendes; Winter 2015, R. Prado)
* AMS131 Introduction to Probability Theory (Summer 2016, D. Draper; Spring 2014, R. Morris)
* AMS203 Introduction to Probability Theory (Fall 2015, R. Prado)
* AMS207 Intermediate Bayesian Modeling (Spring 2017, R. Prado)


### Lab instructor
* AMS 7L Statistical Methods for the Biological, Environmental, and Health Sciences Laboratory (Fall 2016)
